name: Python application test with Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.19
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.19

      - name: Install dependencies
        run: |
          make install
          python -m textblob.download_corpora
      
      - name: Format code
        run: make format

      - name: Lint with pylint
        run: make lint

      - name: Test with pytest
        run: echo "Placeholder for pytest" # Replace this line with `make test` when ready

      

      - name: Build Container
        run: |
          make build
